ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeurls = true
theme = "hugo-theme-slim"
baseURL = "https://nlenblog.netlify.com/"
languageCode = "en-us"
title = "Natalie's Blog"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[Params]
  math = false
  summary = true
  disqusShortname = "nlenblog"
  
  # social
  GithubID = "nlenberger"
  TwitterID = "nlenberger"
  LinkedInID = "nlenberger"
  
[[menu.main]]
  name = "About"
  URL = "/about/"
